import React from "react";
import { PhotocardTemplateProps } from "@/types";
import { PieChart, Minimize2, MoreHorizontal } from "lucide-react";
import Markdown from "react-markdown";
import remarkBreaks from "remark-breaks";

export const ChartCard: React.FC<PhotocardTemplateProps> = ({ data, id }) => {
  return (
    <div
      id={id}
      className="w-[600px] min-h-[400px] bg-white text-zinc-900 p-8 font-sans border border-zinc-200 shadow-xl rounded-xl relative overflow-hidden"
    >
      <div className="flex justify-between items-center mb-8">
        <div>
          <h2 className="text-2xl font-bold tracking-tight mb-1">
            Data Analysis
          </h2>
          <p className="text-zinc-500 text-sm">
            Source: Trust Me Bro Institute of Statistics
          </p>
        </div>
        <div className="bg-zinc-100 p-2 rounded-lg">
          <MoreHorizontal className="text-zinc-400" />
        </div>
      </div>

      <div className="flex gap-8 items-center">
        {/* Fake Pie Chart */}
        <div className="w-48 h-48 rounded-full bg-[#3b82f6] shrink-0 border-[8px] border-zinc-50 shadow-inner relative flex items-center justify-center">
          {/* Slice */}
          <div className="absolute top-0 right-0 w-24 h-24 bg-[#ef4444] rounded-tr-full"></div>
          <div className="absolute bottom-0 right-0 w-24 h-24 bg-[#eab308] rounded-br-full opacity-80"></div>

          {/* Center Hole for Donut */}
          <div className="w-24 h-24 bg-white rounded-full z-10 flex flex-col items-center justify-center shadow-sm">
            <PieChart size={24} className="text-zinc-300 mb-1" />
            <span className="text-xs font-bold text-zinc-400">FIG 1.</span>
          </div>
        </div>

        <div className="flex-1">
          <h3 className="text-lg font-bold mb-4 uppercase tracking-wide border-b border-zinc-100 pb-2">
            Breakdown by Reason
          </h3>

          <ul className="space-y-3 text-sm font-medium">
            <li className="flex items-center gap-3">
              <div className="w-3 h-3 rounded-full bg-[#3b82f6]"></div>
              <span>50% - Delusion</span>
            </li>
            <li className="flex items-center gap-3">
              <div className="w-3 h-3 rounded-full bg-[#ef4444]"></div>
              <span>25% - Audacity</span>
            </li>
            <li className="flex items-center gap-3">
              <div className="w-3 h-3 rounded-full bg-[#eab308]"></div>
              <span>25% - Clout Chasing</span>
            </li>
          </ul>
        </div>
      </div>

      <div className="mt-8 bg-zinc-50 rounded-xl p-6 border border-zinc-100 relative">
        <div className="absolute -top-3 left-6 bg-white border border-zinc-200 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider shadow-sm">
          Executive Summary
        </div>
        <div className="text-lg leading-relaxed text-zinc-800 font-medium prose prose-zinc max-w-none break-words w-full">
          <Markdown remarkPlugins={[remarkBreaks]}>{data.content}</Markdown>
        </div>
      </div>

      <div className="mt-8 pt-4 border-t border-dashed border-zinc-200 flex justify-between items-center text-xs text-zinc-400 font-mono">
        <span>Generated by: @{data.user.handle}</span>
        <span>p &lt; 0.05 (Statistically Significant)</span>
      </div>
    </div>
  );
};
